#Copyright IBM Corp. All Rights Reserved.
#SPDX-License-Identifier: Apache-2.0

# noverify = [
#     "github.com/grpc-ecosystem/go-grpc-middleware"
# ]

ignored = [
    "github.com/hyperledger/fabric-chaincode-evm/evmcc/address",
    "github.com/hyperledger/fabric-chaincode-evm/evmcc/event"
]

[[constraint]]
  version = "1.0.0-alpha5"
  name = "github.com/hyperledger/fabric-sdk-go"

[[constraint]]
  version = "0.0.3"
  name = "github.com/spf13/cobra"

[[constraint]]
  version = "1.9.0"
  name = "go.uber.org/zap"

[[constraint]]
  name = "github.com/onsi/ginkgo"
  revision = "a3b6351eb1ff8e1bfa30b2f55d7e282186ed8fee"

[[constraint]]
  name = "github.com/onsi/gomega"
  version = "1.5.0"

# Constraints from fabric-sdk-gp 
# [[override]]
#   source = "https://github.com/fsnotify/fsnotify/archive/v1.4.7.tar.gz"
#   name = "gopkg.in/fsnotify.v1"

[[override]]
  name = "github.com/cloudflare/cfssl"
  version = "=1.3.1"

[[override]]
  name = "github.com/prometheus/client_golang"
  version = "0.8.0"

[[override]]
  name = "github.com/go-kit/kit"
  version = "0.8.0"

[prune]
  go-tests = true
  unused-packages = true
