#Copyright IBM Corp. All Rights Reserved.
#SPDX-License-Identifier: Apache-2.0

ignored = ["github.com/hyperledger/fabric-chaincode-evm/fab3/types"]

[[constraint]]
  name = "github.com/fsouza/go-dockerclient"
  version = "=1.3.0"

[[override]]
  revision = "0c5f8d2b9b23ab8d23529b3effdcf53bb058298c"
  name = "github.com/docker/docker"

[[override]]
  name = "github.com/docker/libnetwork"
  revision = "19279f0492417475b6bfbd0aa529f73e8f178fb5"

[[constraint]]
  name = "github.com/hyperledger/fabric"
  version = "=1.4.0"

[[constraint]]
  name = "github.com/onsi/ginkgo"
  revision = "a3b6351eb1ff8e1bfa30b2f55d7e282186ed8fee"

[[constraint]]
  name = "github.com/onsi/gomega"
  version = "1.5.0"

[[constraint]]
  branch = "master"
  name = "github.com/tedsuo/ifrit"

[prune]
  go-tests = true
  unused-packages = true

    [[prune.project]]
      name = "github.com/onsi/ginkgo"
      unused-packages = false
      non-go = true
